/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main_java.Main;

/**
 *
 * @author Tri Tue
 */
public class frmHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form frmHoaDon
     */
    public frmHoaDon() {
        initComponents();
        LayDuLieuKhachHang("1");
        LayDuLieuHoaDon("1");
        LayDuLieuTongCong("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKH_CTHD = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbCTHD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btXacNhanThanhToan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTongCong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("xuất hóa đơn");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Hóa đơn thanh toán");

        tbKH_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbKH_CTHD);

        tbCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Size", "Giá sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane7.setViewportView(tbCTHD);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chi tiết hóa đơn");

        btXacNhanThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXacNhanThanhToan.setForeground(new java.awt.Color(255, 0, 51));
        btXacNhanThanhToan.setText("Xác nhận");
        btXacNhanThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanThanhToanActionPerformed(evt);
            }
        });

        tbTongCong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbTongCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tổng cộng"
            }
        ));
        jScrollPane2.setViewportView(tbTongCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btXacNhanThanhToan)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btXacNhanThanhToan)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btXacNhanThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanThanhToanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Đặt hàng thành công! Giao hàng dự kiến 1-2 ngày!");
        String cautruyvan = "";
        cautruyvan = "delete from giohang";
        Main.connection.ExcuteQueryUpdateDB(cautruyvan);
      //  String cautruyvan1="";
        //  cautruyvan1 = "delete from userkhachhang";
       // Main.connection.ExcuteQueryUpdateDB(cautruyvan1);
        frmTrangChu frmTC=new frmTrangChu();
        frmTC.show();
        this.dispose(); 
    
        
        
      
    }//GEN-LAST:event_btXacNhanThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public void LayDuLieuKhachHang(String TrangThai) {
      String cautruyvan = "";
        cautruyvan = "select MaKhachHang,HoTen,SoDienThoai,DiaChi from dangkitaikhoankhachhang,userkhachhang where dangkitaikhoankhachhang.TenDangNhap=userkhachhang.TenDangNhap";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã khách hàng","Họ tên","Số điện thoại","Địa chỉ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbKH_CTHD.setModel(tableModel);
   
        try {
            while (rs.next()) {
           
                Object[] item = new Object[4];
           
                item[0] = rs.getString("MaKhachHang");
                item[1] = rs.getString("HoTen");
                item[2] = rs.getString("SoDienThoai");
                item[3] = rs.getString("DiaChi");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }

    } 
   private void LayDuLieuHoaDon(String trangthai){
               String cautruyvan="";
        cautruyvan="select* from CTHD";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"STT","Mã sản phẩm","Tên sản phẩm","Size","Giá sản phẩm","Số lượng","Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbCTHD.setModel(tableModel);
       int c=0;
        try {
            while (rs.next()) {
             c++;
                Object[] item = new Object[7];
                item[0]=c;
                item[1] = rs.getInt("_MaSanPham");
                item[2] = rs.getString("_TenSanPham");
                 item[3] = rs.getString("_Size");
                item[4] = rs.getString("_GiaSanPham");
               
                  item[5] = rs.getString("_SoLuong");
                
                    item[6] = rs.getString("_ThanhTien");                           
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }
}
   public void LayDuLieuTongCong(String string){
                 String cautruyvan="";
        cautruyvan="select* from giohang";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"Tổng cộng"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbTongCong.setModel(tableModel);
        try {
            while (rs.next()) {
           
                Object[] item = new Object[1];
            
                item[0] = rs.getString("TongTien_");
                                      
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btXacNhanThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tbCTHD;
    private javax.swing.JTable tbKH_CTHD;
    private javax.swing.JTable tbTongCong;
    // End of variables declaration//GEN-END:variables
}
