/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import DataBase.DAO;
import Getset.Product;
import static frm.frmDangNhap.ThongBao;
import static frm.frmDangNhap.ten;
import static frm.frmDangNhap.user;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import main_java.Main;


/**
 *
 * @author Tri Tue
 */
public class frmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangChu
     */
    public frmTrangChu() {
        initComponents();
        //LayDuLieuSanPhamVaoCho("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooserBeanInfo1 = new com.toedter.calendar.JDayChooserBeanInfo();
        jDayChooserBeanInfo2 = new com.toedter.calendar.JDayChooserBeanInfo();
        jYearChooserBeanInfo1 = new com.toedter.calendar.JYearChooserBeanInfo();
        jCalendarBeanInfo1 = new com.toedter.calendar.JCalendarBeanInfo();
        jMonthChooserBeanInfo1 = new com.toedter.calendar.JMonthChooserBeanInfo();
        jTabbedPaneNhanVien = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbHDKH = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbChoMuaHang = new javax.swing.JTable();
        btThemVaoGioHang = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btXoaSanPham = new javax.swing.JButton();
        btThanhToanHoaDon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGioHang = new javax.swing.JTable();
        txtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btLuuSoLuong = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btDangXuat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shop bán giày");

        jTabbedPaneNhanVien.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPaneNhanVien.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPaneNhanVien.setMinimumSize(new java.awt.Dimension(500, 500));
        jTabbedPaneNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPaneNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTabbedPaneNhanVienMouseExited(evt);
            }
        });
        jTabbedPaneNhanVien.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTabbedPaneNhanVienCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));

        jTabbedPane1.setForeground(new java.awt.Color(255, 51, 51));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbKhachHang);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin khách hàng", jPanel5);

        tbHDKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Size", "Giá sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane8.setViewportView(tbHDKH);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("CHI TIẾT HÓA ĐƠN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hóa đơn khách hàng", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPaneNhanVien.addTab("Khách hàng", new javax.swing.ImageIcon(getClass().getResource("/Image/Customer.png")), jPanel2); // NOI18N

        jTabbedPane2.setForeground(new java.awt.Color(255, 51, 0));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("SẢN PHẨM GIÀY TRƯNG BÀY");

        tbChoMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Size", "Giá sản phẩm", "Mô tả"
            }
        ));
        jScrollPane7.setViewportView(tbChoMuaHang);

        btThemVaoGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopping.png"))); // NOI18N
        btThemVaoGioHang.setText("Thêm vào giỏ hàng");
        btThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemVaoGioHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel3))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btThemVaoGioHang)
                .addGap(412, 412, 412))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btThemVaoGioHang)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Shoes shop", jPanel14);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPaneNhanVien.addTab("Shoes shop", new javax.swing.ImageIcon(getClass().getResource("/Image/market.png")), jPanel11); // NOI18N

        jTabbedPane7.setForeground(new java.awt.Color(255, 0, 51));
        jTabbedPane7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane7MouseClicked(evt);
            }
        });

        btXoaSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        btXoaSanPham.setText("Xóa sản phẩm");
        btXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaSanPhamActionPerformed(evt);
            }
        });

        btThanhToanHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/money_03.png"))); // NOI18N
        btThanhToanHoaDon.setText("Thanh toán hóa đơn");
        btThanhToanHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThanhToanHoaDonActionPerformed(evt);
            }
        });

        tbGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Size", "Giá sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        tbGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGioHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbGioHang);

        txtTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongTien.setToolTipText("");
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tổng tiền:");

        jPanel17.setToolTipText("fffff");
        jPanel17.setFocusTraversalPolicyProvider(true);
        jPanel17.setName("Chọn số lượng"); // NOI18N

        jLabel5.setText("Chọn số lượng");

        btLuuSoLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        btLuuSoLuong.setText("Lưu thông tin");
        btLuuSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuSoLuongActionPerformed(evt);
            }
        });

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Số lượng:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLuuSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLuuSoLuong)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btThanhToanHoaDon)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btXoaSanPham)
                            .addComponent(btThanhToanHoaDon)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel17.getAccessibleContext().setAccessibleName("Vhonnj");
        jPanel17.getAccessibleContext().setAccessibleDescription("Chọn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("GIỎ HÀNG");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane7.addTab("Chi tiết hóa đơn", jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        jTabbedPaneNhanVien.addTab("   Hóa đơn ", new javax.swing.ImageIcon(getClass().getResource("/Image/bill.png")), jPanel4); // NOI18N

        btDangXuat.setBackground(new java.awt.Color(204, 204, 255));
        btDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDangXuat.setForeground(new java.awt.Color(255, 102, 102));
        btDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log_out_32.png"))); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.setBorder(new javax.swing.border.MatteBorder(null));
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tell: 0344359333- Hotline: 0964238041- Email: tuetgdd1010@gmail.com");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("PHẦN MỀM BÁN HÀNG ONLINE");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ĐC: 23/6 đường 12, Khu phố 2, P.Linh Chiểu, Q Thủ Đức, Tp.HCM, Việt Nam");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mọi thắc mắc và phản hồi bạn có thể liên hệ trực tiếp với chúng tôi và qua hòm thư phản hồi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneNhanVien.addTab("Thông tin", new javax.swing.ImageIcon(getClass().getResource("/Image/info.png")), jPanel8); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private boolean KiemTraChuaChuVaSo(String chuoi) {
        boolean ketqua = false;
        Pattern p = Pattern.compile("[a-zA-Z][0-9]");
        Matcher m = p.matcher(chuoi);
        if (!(chuoi == chuoi.toLowerCase())) {
            ketqua = m.find();
        }
        return ketqua;
    }
    private void btThanhToanHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThanhToanHoaDonActionPerformed
        // TODO add your handling code here:        
        LayDuLieuKhachHang("1");
          int Vitri=tbGioHang.getSelectedRow();          
          String   cautruyvan = "insert into cthd(_MaSanPham,_TenSanPham,_Size,_GiaSanPham,_SoLuong,_ThanhTien)"
                  + "select MaSanPham_,TenSanPham_,Size_,GiaSanPham_, SoLuong_,ThanhTien_ from giohang ";
                //  + tbChoMuaHang.getValueAt(Vitri,0);
        main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
         UpdateTongTien("1");
        frmHoaDon frmHD=new frmHoaDon();
        frmHD.show();
        this.dispose();
       
    }//GEN-LAST:event_btThanhToanHoaDonActionPerformed

    private void btXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaSanPhamActionPerformed
        // TODO add your handling code here:
        int Vitri=tbGioHang.getSelectedRow();
      //String cautruyvan = Integer.toString(MaNhanVien); 
       
          String   cautruyvan = "delete from giohang where MaSanPham_=" + tbGioHang.getValueAt(Vitri, 1);
        main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
       JOptionPane.showMessageDialog(null, "Bạn xác nhận xóa");
        System.out.println("đã xóa");
         
       LayDuLieuGioHang("1");
       txtTongTien.setText(Integer.toString(getSum()));
    }//GEN-LAST:event_btXoaSanPhamActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        // TODO add your handling code here:
        LayDuLieuKhachHang("1");
        LayDuLieuHoaDonKhachHang("1");
       // UpdateMaKH("1");
    }//GEN-LAST:event_jTabbedPane1MouseClicked
 //public void UpdateMaKH(String string){
   //  String   cautruyvan = "insert into CTHD(MaKhachHang)"
            //      + "select MaKhachHang from dangkitaikhoankhachhang where dangkitaikhoankhachhang.TenDangNhap=userkhachhang.TenDangNhap";                
       // main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
// }
    private void jTabbedPaneNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneNhanVienMouseClicked
        // TODO add your handling code here:
        LayDuLieuSanPhamVaoCho("1");
       
    }//GEN-LAST:event_jTabbedPaneNhanVienMouseClicked

    private void jTabbedPaneNhanVienCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTabbedPaneNhanVienCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPaneNhanVienCaretPositionChanged

    private void jTabbedPaneNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneNhanVienMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPaneNhanVienMouseEntered

    private void jTabbedPaneNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneNhanVienMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPaneNhanVienMouseExited

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        // TODO add your handling code here:
        String cautruyvan = "", cautruyvan1="";
        
         frmDangNhap frmDN=new frmDangNhap();
        frmDN.show();
        this.dispose();
        cautruyvan = "delete from userkhachhang";
        Main.connection.ExcuteQueryUpdateDB(cautruyvan);
        //cautruyvan1 = "delete from giohang";
       // Main.connection.ExcuteQueryUpdateDB(cautruyvan1);
    }//GEN-LAST:event_btDangXuatActionPerformed
  
    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
      // LayDuLieuSanPhamVaoCho("1");       
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void btThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemVaoGioHangActionPerformed
        // TODO add your handling code here:
    
           int Vitri=tbChoMuaHang.getSelectedRow();          
          String   cautruyvan = "insert into giohang(MaSanPham_,TenSanPham_,Size_,GiaSanPham_)"
                  + "select MaSanPham,TenSanPham,Size,GiaSanPham from product  where MaSanPham="
                  + tbChoMuaHang.getValueAt(Vitri,0);
        main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
       //JOptionPane.showMessageDialog(null, "Bạn xác nhận xóa");
        System.out.println("đã thêm sản phẩm chọn vào giỏ hàng");
          //SetTienRow();
            LayDuLieuGioHang("1");
     
       
         
    }//GEN-LAST:event_btThemVaoGioHangActionPerformed
     
    private void LayDuLieuGioHang(String trangthai){
               String cautruyvan="";
        cautruyvan="select* from giohang";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"STT","Mã sản phẩm","Tên sản phẩm","Size","Giá sản phẩm","Số lượng","Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbGioHang.setModel(tableModel);
       int c=0;
        try {
            while (rs.next()) {
             c++;
                Object[] item = new Object[7];
                item[0]=c;
                item[1] = rs.getInt("MaSanPham_");
                item[2] = rs.getString("TenSanPham_");
                 item[3] = rs.getString("Size_");
                item[4] = rs.getString("GiaSanPham_");
               
                  item[5] = rs.getString("SoLuong_");
                
                    item[6] = rs.getString("ThanhTien_");                           
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }
}
   
    private void jTabbedPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane7MouseClicked
        // TODO add your handling code here:
        LayDuLieuGioHang("1");
        // SetTienRow();
    }//GEN-LAST:event_jTabbedPane7MouseClicked

    private void btLuuSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuSoLuongActionPerformed
        // TODO add your handling code here:
      
           btXoaSanPham.setEnabled(true);
        btThanhToanHoaDon.setEnabled(true);    
               SetTienRow();
             // LayDuLieuGioHang("1");             
             txtTongTien.setText(Integer.toString(getSum()));         
    }//GEN-LAST:event_btLuuSoLuongActionPerformed
   public void UpdateTongTien(String string){
       String TongTien;
       TongTien=txtTongTien.getText();
       String cautruyvan="update giohang set TongTien_="+TongTien;
       main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
   }
    public void SetTienBanDau(String TrangThai){
     int Vitri=tbGioHang.getSelectedRow();
     String giasanpham=(String) tbGioHang.getValueAt(Vitri, 4);
      int giaSanPham= Integer.parseInt(giasanpham);
            int ThanhTienBanDau=giaSanPham;
             String thanhTienBanDau= String.valueOf(ThanhTienBanDau);
              String   cautruyvan = "update giohang set MaSanPham_=" + "N'" + tbGioHang.getValueAt(Vitri, 1) + "',ThanhTien_='" + thanhTienBanDau+"'where MaSanPham_=" + tbGioHang.getValueAt(Vitri, 1);
          main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
    }
    public void SetTienRow() {
      String SoLuong;
        String ThanhTien;
        SoLuong=txtSoLuong.getText();
            int Vitri=tbGioHang.getSelectedRow();
            String giasanpham=(String) tbGioHang.getValueAt(Vitri, 4);
            int giaSanPham= Integer.parseInt(giasanpham);
            //int ThanhTienBanDau=giaSanPham;
            //String thanhTienBanDau= String.valueOf(ThanhTienBanDau);
   String   cautruyvan = "update giohang set MaSanPham_=" + "N'" + tbGioHang.getValueAt(Vitri, 1) + "',SoLuong_='" + SoLuong+"'where MaSanPham_=" + tbGioHang.getValueAt(Vitri, 1);
          main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan);
     
      //String soluong=(String) tbGioHang.getValueAt(Vitri, 5);
      
        int soLuong= Integer.parseInt(SoLuong);
        int thanhTien=giaSanPham*soLuong;
        ThanhTien= String.valueOf(thanhTien);
          String   cautruyvan2 = "update giohang set MaSanPham_=" + "N'" + tbGioHang.getValueAt(Vitri, 1) + "',ThanhTien_='" + ThanhTien+  "'where MaSanPham_=" + tbGioHang.getValueAt(Vitri, 1);
          main_java.Main.connection.ExcuteQueryUpdateDB(cautruyvan2);                
          LayDuLieuGioHang("1"); 
    }
    public int getSum(){
      int row=tbGioHang.getRowCount();
      int Sum=0;
  
      for(int i=0;i<row;i++){
        Sum=Sum+Integer.parseInt(tbGioHang.getValueAt(i,6).toString()); 
      }
       
      return Sum;
    }
    private void tbGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGioHangMouseClicked
        // TODO add your handling code here:
        int Vitri=tbGioHang.getSelectedRow();
        txtSoLuong.setText(tbGioHang.getValueAt(Vitri, 5).toString());
    }//GEN-LAST:event_tbGioHangMouseClicked

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTongTienActionPerformed
    
    private boolean KiemTra(String tdn, String mk) {
        boolean kq = false;

        String cautruyvan = "select * from dangkinhanvien where TenDangNhap= '" + tdn + "' and MatKhau= '" + mk + "'";
        System.out.println(cautruyvan);
        ResultSet rs = main_java.Main.connection.ExcuteQueryGetTable(cautruyvan);

        try {
            if (rs.next()) {
                kq = true;
                
                ten=rs.getString("MaKhachHang");
                user=rs.getString("TenDangNhap");
               
            }
        } catch (SQLException ex) {
            System.out.println("lỗi đăng nhập");
        }

        return kq;
    }
    
     public void LayDuLieuSanPhamVaoCho(String TrangThai) {
      String cautruyvan = "";
        cautruyvan = "select * from product ";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã sản phẩm", "Tên sản phẩm","Size","Giá sản phẩm","Mô tả"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbChoMuaHang.setModel(tableModel);
        
        try {
            while (rs.next()) {
                
                Object[] item = new Object[5];
                
                item[0] = rs.getInt("MaSanPham");
                item[1] = rs.getString("TenSanPham");
                item[2] = rs.getString("Size");
                item[3] = rs.getInt("GiaSanPham");
                //item[4] = rs.getDate("Ngay");
                item[4] = rs.getString("MoTa");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }

    }
   /*  public void LayDuLieuNhanVien(String trangthai){
        String cautruyvan="";
        cautruyvan="select* from dangkinhanvien";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"Mã nhân viên","Tên nhân viên","Giới tính","Số điện thoại"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbNhanVien.setModel(tableModel);
      
        try {
            while (rs.next()) {
             
                Object[] item = new Object[4];
               
                item[0] = rs.getInt("MaNhanVien");
                item[1] = rs.getString("TenNhanVien");
                item[2] = rs.getString("GioiTinh");
                item[3] = rs.getString("SoDienThoai");
              
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }
     }*/
   public void ThongBao(String noiDungThongBao,  String tieuDeThongBao, int icon ){
        JOptionPane.showMessageDialog( new JFrame(), noiDungThongBao,
                    tieuDeThongBao, icon );
    }
        
   public void LayDuLieuKhachHang(String TrangThai) {
      String cautruyvan = "";
        cautruyvan = "select MaKhachHang,HoTen,SoDienThoai,DiaChi from dangkitaikhoankhachhang,userkhachhang where dangkitaikhoankhachhang.TenDangNhap=userkhachhang.TenDangNhap";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã khách hàng","Họ tên","Số điện thoại","Địa chỉ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbKhachHang.setModel(tableModel);
   
        try {
            while (rs.next()) {
           
                Object[] item = new Object[4];
           
                item[0] = rs.getString("MaKhachHang");
                item[1] = rs.getString("HoTen");
                item[2] = rs.getString("SoDienThoai");
                item[3] = rs.getString("DiaChi");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }

    } 
    private void LayDuLieuHoaDonKhachHang(String trangthai){
               String cautruyvan="";
        cautruyvan="select* from CTHD ";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"STT","Mã sản phẩm","Tên sản phẩm","Size","Giá sản phẩm","Số lượng","Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbHDKH.setModel(tableModel);
       int c=0;
        try {
            while (rs.next()) {
             c++;
                Object[] item = new Object[7];
                item[0]=c;
                item[1] = rs.getInt("_MaSanPham");
                item[2] = rs.getString("_TenSanPham");
                 item[3] = rs.getString("_Size");
                item[4] = rs.getString("_GiaSanPham");
               
                  item[5] = rs.getString("_SoLuong");
                
                    item[6] = rs.getString("_ThanhTien");                           
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        
        }
    }
    /*private void LayDuLieuHoaDonNhanVien(String trangthai){
               String cautruyvan="";
        cautruyvan="select dangkitaikhoankhachhang.MaKhachHang,_MaSanPham,_TenSanPham,_Size,_GiaSanPham,_SoLuong,_ThanhTien from CTHD,dangkitaikhoankhachhang where CTHD.MaKhachHang= dangkitaikhoankhachhang.MaKhachHang";
        ResultSet rs =Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object obj []=new Object[]{"STT","Mã sản phẩm","Tên sản phẩm","Size","Giá sản phẩm","Số lượng","Thành tiền","Mã khách hàng"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tbHD_NV.setModel(tableModel);
       int c=0;
        try {
            while (rs.next()) {
             c++;
                Object[] item = new Object[8];
                item[0]=c;
                
                item[1] = rs.getInt("_MaSanPham");
                item[2] = rs.getString("_TenSanPham");
                 item[3] = rs.getString("_Size");
                item[4] = rs.getString("_GiaSanPham");
               
                  item[5] = rs.getString("_SoLuong");
                
                    item[6] = rs.getString("_ThanhTien");  
                      item[7] = rs.getString("MaKhachHang"); 
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            
            
            System.out.println(ex.toString());
        }
}*/
    // KẾT THÚC DANH MỤC SẢN PHẨM
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btLuuSoLuong;
    private javax.swing.JButton btThanhToanHoaDon;
    private javax.swing.JButton btThemVaoGioHang;
    private javax.swing.JButton btXoaSanPham;
    private com.toedter.calendar.JCalendarBeanInfo jCalendarBeanInfo1;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo1;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JMonthChooserBeanInfo jMonthChooserBeanInfo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPaneNhanVien;
    private com.toedter.calendar.JYearChooserBeanInfo jYearChooserBeanInfo1;
    private javax.swing.JTable tbChoMuaHang;
    private javax.swing.JTable tbGioHang;
    private javax.swing.JTable tbHDKH;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
//
